### ISSUE TITLE
add a quiz like game

### ISSUE THREAD

**Issue by prerna2712** [SayantaniDeb/Harry-Potter#5]
can add a quiz game where wizards and witches can test their harry potter knowledge. 
Please assign to me.

**Comment by SayantaniDeb** [comment]
sure, you are assigned. @prerna2712 
please dont forget to attach a ss or a video while creating the PR.

**Comment by prerna2712** [comment]
> sure, you are assigned. @prerna2712 
> please dont forget to attach a ss or a video while creating the PR. 

Sure

**Comment by prerna2712** [comment]
why is the issue closed?

**Comment by SayantaniDeb** [comment]
You are already assigned, so now just create a PR with the issue no. And
you're good to go!

**Comment by prerna2712** [comment]
Also wanted to ask if this PR will be accepted for hacktoberfest '21?
